version: 2.1

commands:
  docker-steps:
    parameters:
      docker-build-deps:
        description: "Image build"
        type: steps
        default: []
    steps:
      - checkout
      - run:
          name: "Building image"
          command: "docker build -t spideyz0r/mockzor ."

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - docker-steps:
          docker-build-deps:
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - docker-steps:
          docker-build-deps:
      - run:
          name: "Dockerhub authentication"
          command: "echo $DH_TOKEN | docker login --username=$DH_USERNAME --password-stdin"
      - run:
          name: "Pushing image to Dockerhub"
          command: "docker push spideyz0r/mockzor:latest"

workflows:
  rpmbuilder-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^main$/
      - deploy:
          filters:
            branches:
              only: /^main$/


