version: 2.1

jobs:
  rpmbuilder-image-builder:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: "Building image with docker-compose"
          command: "docker build -t mockzor ."
      - run:
          name: "Pushing image to Dockerhub"
          command: |
          username: mydockerhub-user
          passwd: $DOCKERHUB_PASSWORD

workflows:
  rpmbuilder-workflow:
    jobs:
      - rpmbuilder-image-builder
