version: 2.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Building image"
          command: "docker build -t spideyz0r/mockzor ."
  deploy:
    steps:
      - run:
          name: "Pushing image to Dockerhub"
          command: |
            docker login -u $DH_USERNAME -p $DH_TOKEN
            docker push spideyz0r/mockzor:latest

workflows:
  rpmbuilder-workflow:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^main$/