version: 2.1

commands:
  docker-steps:
    parameters:
      docker-build-deps:
        description: "Image build"
        type: steps
        default: []
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Building image"
          command: "docker build -t spideyz0r/mockzor ."

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - docker-steps:
          docker-build-deps:
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: $DH_USERNAME
          password: $DH_TOKEN
    steps:
      - docker-steps:
          docker-build-deps:
      - run:
          name: "Pushing image to Dockerhub"
          command: |
            echo $DH_TOKEN | docker login -u $DH_USERNAME --password-stdin
            docker push spideyz0r/mockzor:latest

workflows:
  rpmbuilder-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^main$/
      - deploy:
          filters:
            branches:
              only: /^main$/


